name: slack-notification

on: push

jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    env: 
          SLACK_BOT_TOKEN:
          SLACK_CHANNEL_ID:
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_BOT_TOKEN }}
          slack-channel: ${{ env.SLACK_CHANNEL_ID }}
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 
