name: slack-notification

on: push

jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        run: |
          export SLACK_BOT_TOKEN=xoxb-386956934151-2348761920038-Hwb21CAe4JgCUlwU6hDrGSNC
          export SLACK_CHANNEL_ID=C02AWCUCA1W
        with:
          slack-bot-user-oauth-access-token: ${{ SLACK_BOT_TOKEN }}
          slack-channel: ${{ SLACK_CHANNEL_ID }}
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 
